{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5c9d0074-5bc3-494e-aa37-ca6f6c3eb0e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import glob\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fe8f0fa1-55a8-4be0-b029-52847d5dd5b5",
   "metadata": {},
   "outputs": [],
   "source": [
    "RAW_DATA_DIR = \"data/raw\"\n",
    "\n",
    "def profile_datasets():\n",
    "    print(\"Phase 1: Profiling Datasets\")\n",
    "\n",
    "    csv_files = glob.glob(os.path.join(RAW_DATA_DIR, \"*.csv\"))\n",
    "\n",
    "    if not csv_files:\n",
    "        print(\"No CSV files found in data/raw\")\n",
    "        return {}\n",
    "\n",
    "    datasets = {}\n",
    "\n",
    "    for file_path in csv_files:\n",
    "        file_name = os.path.basename(file_path)\n",
    "        df = pd.read_csv(file_path)\n",
    "        datasets[file_name] = df\n",
    "\n",
    "        print(\"\\n\" + \"=\"*50)\n",
    "        print(f\"Dataset: {file_name}\")\n",
    "        print(\"=\"*50)\n",
    "        print(f\"Shape: {df.shape}\")\n",
    "        print(\"\\nData Types:\")\n",
    "        print(df.dtypes)\n",
    "        print(\"\\nHead Preview:\")\n",
    "        print(df.head())\n",
    "\n",
    "        null_counts = df.isnull().sum().sum()\n",
    "        if null_counts > 0:\n",
    "            print(f\"Anomaly: Found {null_counts} missing values in this file.\")\n",
    "\n",
    "    return datasets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d19a6b99-93fb-4248-a5bb-c011733cd1bc",
   "metadata": {},
   "outputs": [],
   "source": [
    "def explore_fund_master(datasets):\n",
    "    print(\"\\n Phase 2: Exploring Fund Master Metadata\")\n",
    "\n",
    "    master_file = \"fund_master.csv\"\n",
    "\n",
    "    if master_file in datasets:\n",
    "        df_master = datasets[master_file]\n",
    "\n",
    "        if \"scheme_name\" in df_master.columns:\n",
    "            print(\"\\nExposed Columns in Live Master API:\", list(df_master.columns))\n",
    "            \n",
    "            df_master['extracted_amc'] = df_master['scheme_name'].apply(lambda x: str(x).split('-')[0].strip())\n",
    "            print(\"\\nUnique Asset Management Companies Sample:\")\n",
    "            print(df_master['extracted_amc'].unique()[:10])\n",
    "\n",
    "        print(\"\\nAMFI Scheme Code Structure:\")\n",
    "        print(\"Standard AMFI codes are unique 6-digit numeric identifiers\")\n",
    "    else:\n",
    "        print(f\"{master_file} not found in dataset\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "623a1388-b558-4806-9dcb-36bb1bd1f502",
   "metadata": {},
   "outputs": [],
   "source": [
    "def validate_amfi_codes(datasets):\n",
    "    print(\"\\nPhase 3: Data Quality & Cross-Validation Summary\")\n",
    "\n",
    "    master_file = \"fund_master.csv\"\n",
    "\n",
    "    if master_file in datasets:\n",
    "        df_master = datasets[master_file]\n",
    "        \n",
    "        global_master_codes = set(df_master[\"scheme_code\"].dropna().astype(str).unique())\n",
    "\n",
    "        target_codes = set()\n",
    "        for name, df in datasets.items():\n",
    "            if name != master_file and \"scheme_code\" in df.columns:\n",
    "                target_codes.update(df[\"scheme_code\"].astype(str).unique())\n",
    "\n",
    "        missing_targets = target_codes - global_master_codes\n",
    "\n",
    "        print(\"\\nDATA QUALITY REPORT SUMMARY:\")\n",
    "        print(f\"• Unique Codes in Global Master File: {len(global_master_codes)}\")\n",
    "        print(f\"• Unique Target Codes Ingested: {len(target_codes)} (Targeting HDFC & 5 Bluechips)\")\n",
    "\n",
    "        if missing_targets:\n",
    "            print(f\"CRITICAL ANOMALY: Your ingested targets {missing_targets} don't exist in the global master list!\")\n",
    "        else:\n",
    "            print(\"Referential Integrity Check: Passed\")\n",
    "    else:\n",
    "        print(\"Validation: 'fund_master.csv' must be added to data/raw\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "615e33ad-46c7-47c1-990a-2e4ad5802a20",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Phase 1: Profiling Datasets\n",
      "\n",
      "==================================================\n",
      "Dataset: axis_bluechip.csv\n",
      "==================================================\n",
      "Shape: (3580, 4)\n",
      "\n",
      "Data Types:\n",
      "scheme_code      int64\n",
      "scheme_name     object\n",
      "date            object\n",
      "nav            float64\n",
      "dtype: object\n",
      "\n",
      "Head Preview:\n",
      "   scheme_code                                        scheme_name        date  \\\n",
      "0       119092  HDFC Money Market Fund - Growth Option - Direc...  22-06-2026   \n",
      "1       119092  HDFC Money Market Fund - Growth Option - Direc...  19-06-2026   \n",
      "2       119092  HDFC Money Market Fund - Growth Option - Direc...  18-06-2026   \n",
      "3       119092  HDFC Money Market Fund - Growth Option - Direc...  17-06-2026   \n",
      "4       119092  HDFC Money Market Fund - Growth Option - Direc...  16-06-2026   \n",
      "\n",
      "         nav  \n",
      "0  6199.4871  \n",
      "1  6195.7815  \n",
      "2  6194.6520  \n",
      "3  6193.3504  \n",
      "4  6191.8120  \n",
      "\n",
      "==================================================\n",
      "Dataset: hdfc_top_100_direct.csv\n",
      "==================================================\n",
      "Shape: (3106, 4)\n",
      "\n",
      "Data Types:\n",
      "scheme_code      int64\n",
      "scheme_name     object\n",
      "date            object\n",
      "nav            float64\n",
      "dtype: object\n",
      "\n",
      "Head Preview:\n",
      "   scheme_code                                scheme_name        date  \\\n",
      "0       125497  SBI Small Cap Fund - Direct Plan - Growth  22-06-2026   \n",
      "1       125497  SBI Small Cap Fund - Direct Plan - Growth  19-06-2026   \n",
      "2       125497  SBI Small Cap Fund - Direct Plan - Growth  18-06-2026   \n",
      "3       125497  SBI Small Cap Fund - Direct Plan - Growth  17-06-2026   \n",
      "4       125497  SBI Small Cap Fund - Direct Plan - Growth  16-06-2026   \n",
      "\n",
      "        nav  \n",
      "0  204.1263  \n",
      "1  202.0761  \n",
      "2  200.9565  \n",
      "3  199.8302  \n",
      "4  198.6152  \n",
      "\n",
      "==================================================\n",
      "Dataset: icici_bluechip.csv\n",
      "==================================================\n",
      "Shape: (3322, 4)\n",
      "\n",
      "Data Types:\n",
      "scheme_code      int64\n",
      "scheme_name     object\n",
      "date            object\n",
      "nav            float64\n",
      "dtype: object\n",
      "\n",
      "Head Preview:\n",
      "   scheme_code                                        scheme_name        date  \\\n",
      "0       120503  Axis ELSS Tax Saver Fund - Direct Plan - Growt...  22-06-2026   \n",
      "1       120503  Axis ELSS Tax Saver Fund - Direct Plan - Growt...  19-06-2026   \n",
      "2       120503  Axis ELSS Tax Saver Fund - Direct Plan - Growt...  18-06-2026   \n",
      "3       120503  Axis ELSS Tax Saver Fund - Direct Plan - Growt...  17-06-2026   \n",
      "4       120503  Axis ELSS Tax Saver Fund - Direct Plan - Growt...  16-06-2026   \n",
      "\n",
      "        nav  \n",
      "0  108.4681  \n",
      "1  107.9636  \n",
      "2  108.0081  \n",
      "3  107.5348  \n",
      "4  107.0140  \n",
      "\n",
      "==================================================\n",
      "Dataset: kotak_bluechip.csv\n",
      "==================================================\n",
      "Shape: (3316, 4)\n",
      "\n",
      "Data Types:\n",
      "scheme_code      int64\n",
      "scheme_name     object\n",
      "date            object\n",
      "nav            float64\n",
      "dtype: object\n",
      "\n",
      "Head Preview:\n",
      "   scheme_code                                       scheme_name        date  \\\n",
      "0       120841  quant Mid Cap Fund - Growth Option - Direct Plan  22-06-2026   \n",
      "1       120841  quant Mid Cap Fund - Growth Option - Direct Plan  19-06-2026   \n",
      "2       120841  quant Mid Cap Fund - Growth Option - Direct Plan  18-06-2026   \n",
      "3       120841  quant Mid Cap Fund - Growth Option - Direct Plan  17-06-2026   \n",
      "4       120841  quant Mid Cap Fund - Growth Option - Direct Plan  16-06-2026   \n",
      "\n",
      "        nav  \n",
      "0  252.0694  \n",
      "1  251.5713  \n",
      "2  249.1553  \n",
      "3  246.3925  \n",
      "4  245.2402  \n",
      "\n",
      "==================================================\n",
      "Dataset: nippon_large_cap.csv\n",
      "==================================================\n",
      "Shape: (3313, 4)\n",
      "\n",
      "Data Types:\n",
      "scheme_code      int64\n",
      "scheme_name     object\n",
      "date            object\n",
      "nav            float64\n",
      "dtype: object\n",
      "\n",
      "Head Preview:\n",
      "   scheme_code                                        scheme_name        date  \\\n",
      "0       118632  Nippon India Large Cap Fund - Direct Plan Grow...  22-06-2026   \n",
      "1       118632  Nippon India Large Cap Fund - Direct Plan Grow...  19-06-2026   \n",
      "2       118632  Nippon India Large Cap Fund - Direct Plan Grow...  18-06-2026   \n",
      "3       118632  Nippon India Large Cap Fund - Direct Plan Grow...  17-06-2026   \n",
      "4       118632  Nippon India Large Cap Fund - Direct Plan Grow...  16-06-2026   \n",
      "\n",
      "        nav  \n",
      "0  101.3654  \n",
      "1  100.7824  \n",
      "2  100.9901  \n",
      "3  100.6040  \n",
      "4  100.0048  \n",
      "\n",
      "==================================================\n",
      "Dataset: sbi_bluechip.csv\n",
      "==================================================\n",
      "Shape: (3251, 4)\n",
      "\n",
      "Data Types:\n",
      "scheme_code      int64\n",
      "scheme_name     object\n",
      "date            object\n",
      "nav            float64\n",
      "dtype: object\n",
      "\n",
      "Head Preview:\n",
      "   scheme_code                                        scheme_name        date  \\\n",
      "0       119551  Aditya Birla Sun Life Banking & PSU Debt Fund ...  22-06-2026   \n",
      "1       119551  Aditya Birla Sun Life Banking & PSU Debt Fund ...  19-06-2026   \n",
      "2       119551  Aditya Birla Sun Life Banking & PSU Debt Fund ...  18-06-2026   \n",
      "3       119551  Aditya Birla Sun Life Banking & PSU Debt Fund ...  17-06-2026   \n",
      "4       119551  Aditya Birla Sun Life Banking & PSU Debt Fund ...  16-06-2026   \n",
      "\n",
      "        nav  \n",
      "0  105.9850  \n",
      "1  105.9219  \n",
      "2  105.9003  \n",
      "3  105.8482  \n",
      "4  105.8455  \n",
      "\n",
      " Phase 2: Exploring Fund Master Metadata\n",
      "fund_master.csv not found in dataset\n",
      "\n",
      "Phase 3: Data Quality & Cross-Validation Summary\n",
      "Validation: 'fund_master.csv' must be added to data/raw\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    loaded_dfs = profile_datasets()\n",
    "    explore_fund_master(loaded_dfs)\n",
    "    validate_amfi_codes(loaded_dfs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1524b8dd-2c32-4ebc-a1aa-4ff53f791eeb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "23939ab2-03d6-44ac-b1c6-aee2088b02e4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "29fdb83d-0e3d-433c-953f-21279e64eda3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
